# Generated by Django 4.2.15 on 2024-09-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_remove_order_cart_order_carts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='sity',
            new_name='city',
        ),
    ]
