# Generated by Django 4.2.15 on 2024-09-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='user',
        ),
    ]
