# Generated by Django 4.2.15 on 2024-09-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Питання')),
                ('answer', models.TextField(max_length=5000, verbose_name='Відповідь')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Часті запитання',
                'verbose_name_plural': 'Часті запитання',
                'db_table': 'faq',
                'ordering': ['created_at'],
            },
        ),
    ]
